### ISSUE TITLE
多开如何正常运行

### ISSUE THREAD

**Issue by Dadaxyu** [cndaqiang/WZRY#35]
1、通过命令行多开，进入到组队模式，房间匹配界面后，一直在循环检测，两个端未进行组队，请问如何修改配置或者代码可以正常运行，是否存在什么前置要求？
2、同时运行多个模拟器，如何配置每个端都是单人模式
![image](https://github.com/user-attachments/assets/d25fa70a-de95-43cf-8437-a54ec098e8f3)
![image](https://github.com/user-attachments/assets/6312d4f0-d070-4028-b98f-082256a17bb2)

**Comment by cndaqiang** [comment]
> 1、通过命令行多开，进入到组队模式，房间匹配界面后，一直在循环检测，两个端未进行组队，请问如何修改配置或者代码可以正常运行，是否存在什么前置要求？

源代码中，房主的头像是我的账号，你要替换代码中的静态图片为你的，进入在房间后，用AirTEST里截图就行了
```
        self.房主头像 = Template(r"tpl1716782981770.png", record_pos=(0.354, -0.164), resolution=(960, 540), target_pos=9)
        self.房主房间 = Template(r"tpl1700284856473.png", record_pos=(0.312, -0.17), resolution=(1136, 640), target_pos=2)
```
**此外，我设置的是小号，进入大号的房间，需要大号开放进房权限，我是大小号建立了好友关系，好友可以直接进房**
 @Dadaxyu

**Comment by cndaqiang** [comment]
> 2、同时运行多个模拟器，如何配置每个端都是单人模式
方式1. 各个模拟器完全独立，不互相干扰, 单独运行脚本即可，每个脚本的配置文件`config.node.txt`里面写好他们各自的node，以及`totalnode=1`
例如我的配置文件`config.1.txt`, 只控制其中`mynode = 1`的模拟器
```
[client]
# 仅在单进程时有效
mynode = 1
# 多进程时，多进程的数目
totalnode = 1

# 多进程配置
multiprocessing = True
#默认读入字符串, 不要添加引号
MuMudir = D:\Program Files\Netease\MuMu Player 12\shell
#
LINK_dict = {
    0: "Android:///127.0.0.1:16384",
    1: "Android:///127.0.0.1:16416",
    2: "Android:///127.0.0.1:5555"}
```
```
%USERPROFILE%\AppData\Local\anaconda3\python.exe wzry.py  config.1.txt
```
在另一个cmd里
```
%USERPROFILE%\AppData\Local\anaconda3\python.exe wzry.py  config.2.txt
```

---
方式2. 两个账号彼此校验，一方掉线，另一方也强制停止。和组队相同的方式运行，把组队时间设置< 0,任何时间都不进行组队。
```
self.限时组队时间 = 7
```

@Dadaxyu

**Comment by Dadaxyu** [comment]
![image](https://github.com/user-attachments/assets/d12c71e6-3436-4884-95b1-9215bbb97234)
最新脚本运行报错，请问要怎么修复？
@cndaqiang

**Comment by cndaqiang** [comment]
> ![image](https://private-user-images.githubusercontent.com/44860020/370622389-d12c71e6-3436-4884-95b1-9215bbb97234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTM0NTQsIm5iZiI6MTcyNzI1MzE1NCwicGF0aCI6Ii80NDg2MDAyMC8zNzA2MjIzODktZDEyYzcxZTYtMzQzNi00ODg0LTk1YjEtOTIxNWJiYjk3MjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA4MzIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZmI2NWNlOTBjNGNkNjk5ZDRiYjQyOTIwOTBlZmNkMjlhYmI3NWQ1ZjNmYWUxNjljM2VhZjgxNjUzZDVhZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cHEW5OyPHqD_NVdhZJNyfoU-vG_ViyJLEJiJDbRik94) 最新脚本运行报错，请问要怎么修复？ @cndaqiang

```
python -m pip install airtest_mobileauto --upgrade
```
@Dadaxyu
