### ISSUE TITLE
作者有时间加入新功能吗

### ISSUE THREAD

**Issue by bttao** [cndaqiang/WZRY#36]
有空的话, 可以加入1v1单挑或者边境之战吗,   1v1只要能动动键盘,放放技能就行,一般不会扣分,        边境之战,挂机不会扣分,   
这两个可以, 都可以加熟练度到大红花,     我的要求会不会太多了doge

**Comment by cndaqiang** [comment]
1v1大概率会被举报的
我测试了边境之战，蓝豆英雄一局大约增加4点熟练度，星耀局人机27+熟练度，也都能熟练度变红
一天十局星耀人机等于要打50局的边境之战，边境之战的性价比不高呀
打完十局星耀后，就快要被健康模式警告了 @bttao

**Comment by bttao** [comment]
感谢大哥
