### ISSUE TITLE
无法自动选择熟练度最低的英雄

### ISSUE THREAD

**Issue by GenLiya** [cndaqiang/WZRY#40]
![image](https://github.com/user-attachments/assets/459919bc-7a28-4f79-b0c2-89cfa67f5cd5)
我y'j已经下载了解压包，并将指导文件中要求创建的文件新建并粘贴文字，但是并没有选择熟练度最低的英雄

**Comment by cndaqiang** [comment]
`node`是你虚拟机编号的意思，根据你config.in中定义的mynode指定
例如你之前issues #38 中的截图https://github.com/cndaqiang/WZRY/issues/38#issue-2587733756
```
mynode=1
```
则这里应该是`WZRY.1.对战前插入.txt`
@GenLiya

**Comment by cndaqiang** [comment]
@GenLiya 你应该已经阅读过了
我的熟练度字典是几个月之前的，不包括新英雄影，你介意的话，自己去生成字典即可#13 
https://github.com/cndaqiang/WZRY/issues/13#issuecomment-2205392546

**Comment by GenLiya** [comment]
![image](https://github.com/user-attachments/assets/b453cbac-9522-4297-92f0-b74b83ef2cd8)
![image](https://github.com/user-attachments/assets/86b8e1be-3bab-46d0-87eb-2db2458ee61d)
我已经根据模拟器的编号将node更改为了10，现在的问题是它每次都会选择熟练度最高的，

**Comment by cndaqiang** [comment]
参见 #47
