### ISSUE TITLE
常见问题收录

### ISSUE THREAD

**Issue by cndaqiang** [cndaqiang/WZRY#42]
## 有问题，发布一个新的issue
或者查看历史[issue](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/issues?q=is%3Aissue+is%3Aclosed)
## 本issue用于收录常见问题

**Comment by cndaqiang** [comment]
## 进入不了大厅
#39 
## 原因
* 活动更新了大厅的图标（即使不更新图标，也是可以进入大厅的）
* 多等一会
* * 如果是本脚本启动的模拟器，则会先执行登录命令
* * 提前把王者关闭，让本脚本启动王者，也会执行登录命令
* * 如果你没有配置模拟器的参数，本脚本在运行时，不知道模拟器当前处在什么界面，会进行大厅、房间、对战等状态的判断，在最后无法判断出来后，本脚本会重新打开关闭王者，进行登录。十分钟以内可以进入，要有耐心。

**Comment by cndaqiang** [comment]
## 如何设置配置文件
#38 

解决方案
* 1. `python WZRY.py config.in`
* 2. `config_file = "config.in"`
* 详细解释见 #38

**Comment by cndaqiang** [comment]
## 无法自动选择熟练度最低的英雄
#40 

* 配置文件写错了: 要把`WZRY.node.对战前插入.txt`替换为配置文件中的`mynode`
* 如`WZRY.1.对战前插入.txt`,`WZRY.0.对战前插入.txt`
* `WZRY.node.对战前插入.txt`仅对`mynode`对应的虚拟机生效

**Comment by cndaqiang** [comment]
## 试问这个脚本可以直接拿去打排位或者匹配吗？
#37 
可以，但是会被扣信誉分，不推荐

## 有计划提供apk么
#17 
* 无计划, 该项目初衷是为了脚本、模拟器7*24h在服务器上完成运行的

**Comment by cndaqiang** [comment]
## 多开如何正常运行 
#35 
* 源代码中，房主的头像是我的账号，你要替换代码中的静态图片为你的，进入在房间后，用AirTEST里截图就行了
* 详见 #35

**Comment by cndaqiang** [comment]
## 使用项目默认的配置文件config.in报错 
#43 
说明
* 认真读[howto](https://cndaqiang.github.io/WZRY/howtorun.html)啊喂
* `config.in` 是用于参考的，不是你实际运行应该采用的配置文件
* 常见的雷电模拟器、BlueStack的默认adb是`127.0.0.1:5555`, 可以使用配置文件，直接运行`python wzry.py`
* 其他模拟器或者多开时，才需要配置`config.in`,  配置的方法参考[howto](https://cndaqiang.github.io/WZRY/howtorun.html), 运行`python wzry.py config.in`
* 另外建议把`config.in`复制一份进行修改，配置文件的名字可以是任意的，比如我常用`python wzry.py config.win.txt`

@NonFelm

**Comment by cndaqiang** [comment]
## ARM设备无法执行adb
* 使用linux的用户都是高手，你一眼就能看出这个解决办法
```
cd ~/.local/lib/python3.10/site-packages/airtest/core/android/static/adb/linux
mv adb adb.bak
ln -s /usr/bin/adb .
```

## 苹果笔记本(MacOS)无法控制安卓
* 在苹果设备上使用python脚本的你，这个命令对你来说也是小意思
```
chmod +x ~/anaconda3/lib/python3.11/site-packages/airtest/core/android/static/adb/mac/adb
```

**Comment by NonFelm** [comment]
一开始我创了一个新的配置文件

[client]
totalnode = 2
# 不设置LDPlayerdir，脚本也可以正常运行。
# 设置后支持关闭、启动、隐藏模拟器等操作，7*24h运行时更省电。
LDPlayerdir = D:\GreenSoft\LDPlayer 改成了我的路径
multiprocessing = True
LINK_dict = {
    0: "Android:///127.0.0.1:5555",
    1: "Android:///127.0.0.1:5557"}
但是运行后界面消失（我想要有界面的效果），也不断报错（忘截图了），才重新从开一个号试一试的

________________________________
发件人: cndaqiang ***@***.***>
发送时间: 2024年10月18日 18:25
收件人: cndaqiang/WZRY ***@***.***>
抄送: NonFelm ***@***.***>; Mention ***@***.***>
主题: Re: [cndaqiang/WZRY] 常见问题收录 (Issue #42)


ARM设备无法执行adb

  *   使用linux的用户都是高手，你一眼就能看出这个解决办法

cd ~/.local/lib/python3.10/site-packages/airtest/core/android/static/adb/linux
mv adb adb.bak
ln -s /usr/bin/adb .


苹果笔记本(MacOS)无法控制安卓

  *   在苹果设备上使用python脚本的你，这个命令对你来说也是小意思

chmod +x ~/anaconda3/lib/python3.11/site-packages/airtest/core/android/static/adb/mac/adb


―

**Comment by cndaqiang** [comment]
## 在 cmd/powershell 中执行时，程序偶尔卡住，回车后继续
windows的cmd默认开启了快速编辑模式，如果在执行过程中，有复制选中等行为，会强制让命令停住

**搜索取消windows cmd快速编辑**，下面是一些解决方案
* https://www.cnblogs.com/mq0036/p/12100632.html
* https://www.cnblogs.com/LRolinx/p/16695671.html

**Comment by cndaqiang** [comment]
## 触摸对战不生效
#45 
**不要直接复制我的配置文件，读一下，根据你的情况进行修改**

开启触摸对战的几种方法
1. 在`WZRY.mynode.对战前插入.txt`中填入`self.触摸对战 = True`
2. 在运行目录创建一个 `WZRY.TOUCH.txt`文件.
3. ~~直接修改源码~~不推荐

## 标准对战不生效
同上

开启标准对战的几种方法
1. 在`WZRY.mynode.对战前插入.txt`中填入`self.触摸对战 = True`
2. 在运行目录创建一个 `WZRY.mynode.标准模式.txt`文件
3. ~~直接修改源码~~不推荐

@NonFelm

**Comment by cndaqiang** [comment]
## 运行之后，很快接黑屏了，我怎么查看运行报错的信息
在配置文件后面添加
```
[control]
#将运行日志输出到文件，适合于监控windows的计划任务
logfile={
    0: "result.0.txt",
    1: "result.1.txt"}
```
会将`mynode`的模拟器日志输出到`result.mynode.txt`, 提issues时，可以附上这个日志

**Comment by cndaqiang** [comment]
## 我想精准控制每一局采用何种模式对战，怎么改配置文件
#49 

以第一次进行青铜+标准人机+触摸对战为例，在`WZRY.mynode.对战前插入.txt`中插入
* self.jinristep变量代表今天的第几次对战
```
self.青铜段位 = False
self.标准模式 = False
self.触摸对战 = False
if self.jinristep = 1: self.青铜段位 = True
if self.jinristep = 1: self.标准模式 = True
if self.jinristep = 1: self.触摸对战 = True
```

**Comment by cndaqiang** [comment]
## 模块[airtest_mobileauto]不存在, 尝试安装
#50 

```
模块[airtest_mobileauto]不存在, 尝试安装
Traceback (most recent call last):
File "G:\WZRY\wzry.py", line 2902, in
task_manager = TaskManager(config_file, wzry_task, 'RUN')
^^^^^^^^^^^
NameError: name 'TaskManager' is not defined
```

* 读一下[手册](https://github.com/cndaqiang/WZRY/blob/master/howtorun.md)啊, 第一条就是安装依赖
```
python -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple  --upgrade
```

**Comment by cndaqiang** [comment]
## 星耀模式无法组队
#51 

星耀局的组队没有意义，所以我在代码里禁止了，因为
* * 刷人机任务，刷金币，刷熟练度，只用青铜局就够了
* * 蓝色熟练度提升到红色熟练度才需要星耀局人机，星耀局单人模式比组队模式的胜率更高，经验更多（毕竟除了你还有一个真人在打游戏）
* * 每个账号每天星耀限制10局，不同的账户剩余局数不同。当一个账户达到上限时，组队失败

强制开启星耀组队见 #51

**Comment by cndaqiang** [comment]
## 加好友指导一下
* 不加好友
* 先阅读[WZRY.pdf](https://cndaqiang.github.io/WZRY/doc/WZRY.pdf)
* 再阅读 https://cndaqiang.github.io/WZRY/howtorun.html

**Comment by cndaqiang** [comment]
## 控制游戏只打N局，打完就退出，怎么操作
#52 

* 在wzry.py所在目录，新建一个空文件`WZRY.oneday.txt`
* 在`WZRY.node.临时初始化.txt`中填写
```
#4是对战总次数
 self.jinristep >=  4:  self.对战时间[1]=self.对战时间[0]+0.1
```
* 更复杂的配置可以见 https://github.com/cndaqiang/WZRY/issues/13#issuecomment-2197922847

**Comment by cndaqiang** [comment]
## 如何使用模拟战刷信誉分
* 在娱乐模式的快捷入口添加王者模拟战
* 自己手动进去打一轮(同意协议，领取礼包，预设阵容)
* 返回大厅
* 在`WZRY.node.对战前插入.txt`中添加`self.对战模式 = "5v5匹配"`, 执行`wzry.py`代码
![image](https://github.com/user-attachments/assets/3cbde96b-2e89-49bb-b899-dc3ff33c8e3c)

**Comment by cndaqiang** [comment]
## 苹果手机怎么使用
* **不回复相关问题**
* 从[1.2.2](https://github.com/cndaqiang/WZRY/releases/tag/1.2.2)版本开始，我的苹果账户已经刷完了，没有精力继续测试维护
* ios部分的代码，太久没有更新，能否使用请自行尝试。
* 这是我当初的运行环境: [Android/IOS移动平台自动化脚本(基于AirTest)](https://cndaqiang.github.io/2023/11/10/MobileAuto/)

**Comment by cndaqiang** [comment]
## 战令、活跃礼包无法领取
#53 

* 王者的礼包界面天天变来变去，不同分辨率甚至QQ和微信登录后的界面也有很大差异，很难一个代码适配所有设备
* 自己查看屏幕输出，找到代码相应位置，用AirtestIDE截取你设备的图像，进行替换
* 也可以尝试，下载最新的release程序，**只复制你的config.win.txt文件到新代码目录，重新进行礼包位置矫正**

**Comment by cndaqiang** [comment]
## 如何刷完任务自动关机
#54 
* 及时阅读手册更新，
* 看看我的BlueStack的配置文件 https://cndaqiang.github.io/WZRY/howtorun.html
* 看看其他模拟器的配置文件 https://cndaqiang.github.io/WZRY/doc/config.example.html
* 添加上`XXXdir=模拟器安装路径`，`XXX_Instance={0: "0",1, "1"}` 是模拟器的内部编号。
* * XXX代表模拟器的名字，具体参考 https://cndaqiang.github.io/WZRY/doc/config.example.html
* * `XXX_Instance`内部编号的含义，如果你是全新安装的模拟器，并且每个多开都是wary，可以不设置`XXX_Instance`
* * 如果你的模拟器好多多开，很多账号很多游戏，那你就读读我是怎么配置Bluestack的 https://cndaqiang.github.io/WZRY/doc/config.example.html，以及内部编号到底是什么（https://cndaqiang.github.io/WZRY/howtorun.html以及本issues）
* * 简单点，就是在多开平台中创建模拟器的快捷方式到桌面，然后再查看快捷方式的属性，最后几个字就是Instance


*

**Comment by cndaqiang** [comment]
全新版本更新，关闭旧的手册、issues、主页等内容
