### ISSUE TITLE
使用项目默认的配置文件config.in报错

### ISSUE THREAD

**Issue by NonFelm** [cndaqiang/WZRY#43]
**先设置了雷电模拟器：分辨率960*540(dpi160)、ADB调试：远程连接(不推荐)。
打开了雷电-王者荣耀，并登录进入到大厅。cmd cd进入项目文件夹目录，执行命令python WZRY.py config.in**
_小白虚心求教！_
config.in文件是默认的
[client]
mynode = 0
LINK_dict = {0: "Android:///127.0.0.·：16384"}

#
[control]
prefix="ttt"
logger_level=0
figdir=assets
logfile={0: "result.0.txt"}
#
报错图如下：
![1](https://github.com/user-attachments/assets/d7d204e1-d7f1-4de6-9a37-858538cef567)
![2](https://github.com/user-attachments/assets/e13eba25-c071-4f62-a9eb-3b8f333188e5)
![3](https://github.com/user-attachments/assets/6ba8be40-0ba7-46ca-aa0a-5392bc5fe011)

**Comment by cndaqiang** [comment]
@NonFelm 
确保你开启了雷电的adb端口后，雷电的adb应该是`127.0.0.1:5555`, 默认的`config.in`是给你提供的模板。

* 你直接运行，就是雷电的`127.0.0.1:5555`
```
python wzry.py
```
* 如果你要使用配置文件，参考[使用手册](https://cndaqiang.github.io/WZRY/howtorun.html)

**Comment by NonFelm** [comment]
我修改了LINK_dict = {0: "Android:///127.0.0.1:5555"}，可以正常打开游戏，但**在登陆界面等了许久不会进入游戏。**
我手动进入之后，**一直停留在大厅**了。
#
![1](https://github.com/user-attachments/assets/f4210868-0e7c-433a-bcb6-170e4382198d)
![2](https://github.com/user-attachments/assets/5743c6df-fcc8-4f65-96cc-d4993e6f328b)

**Comment by cndaqiang** [comment]
@NonFelm 
周年庆图标临时发生变化，下载临时图标解压即可

下载这个
* https://github.com/cndaqiang/WZRY/issues/8#issuecomment-2418461016
* 解压完的示例 #8 

相关连接
#41 
https://github.com/cndaqiang/WZRY/issues/42#issuecomment-2418495002
