### ISSUE TITLE
触摸对战不生效

### ISSUE THREAD

**Issue by NonFelm** [cndaqiang/WZRY#45]
example的WZRY.0.对战前插入，**触摸模式、标准模式**=Ture，不起作用
进去选的还是快速模式，星耀局。一般来说**刷活动任务**得标准模式才行吧
@cndaqiang
#
![屏幕截图 2024-10-19 103256](https://github.com/user-attachments/assets/88ae264d-5760-4542-81d9-031b2fc9ffae)
![触摸对战](https://github.com/user-attachments/assets/d3253b05-82d3-4743-bc98-b64d6383c0a8)
![3](https://github.com/user-attachments/assets/042593e1-1054-4f02-88a1-0c6c8ab2b117)

**Comment by cndaqiang** [comment]
@NonFelm 

这是我的配置文件，你不能直接搬过来就用，
**你首先读一下里面写的是什么？**
```
# 每天早上前两局，标准模式
if self.组队模式 and self.jinristep <= 1: self.标准模式 = self.触摸对战 = True
# 组队的时候不要赢，这样获得的战令经验不到上限，可以额外从营地领经验
# 周日大概率是在刷友情币等项目，不要开模拟对战
if self.组队模式 and self.Tool.time_getweek() < 6: self.触摸对战 = True
```
在开启组队`self.组队模式=True`的前提下，这个命令才有效


你应该直接设置
```
self.标准模式 = self.触摸对战 = True
```
