### ISSUE TITLE
房主房间.图片指的是什么？

### ISSUE THREAD

**Issue by NonFelm** [cndaqiang/WZRY#46]
**房主头像**指的是下图红色圆圈嘛？
![屏幕截图 2024-10-19 205354](https://github.com/user-attachments/assets/d519a45a-b85c-406f-8e3e-460562f9478d)

#
那**房主房间**的图片是啥咧...
![屏幕截图 2024-10-19 205440](https://github.com/user-attachments/assets/7b504927-1c3a-4550-bbbc-89f4237f3134)
@cndaqiang

**Comment by cndaqiang** [comment]
@NonFelm 你可以查看源码目录中`assets/tpl1716782981770.png`文件，
![房主房间](https://github.com/cndaqiang/WZRY/blob/master/assets/tpl1716782981770.png)

组队方式是通过亲密好友自动进房不用验证实现的
* 大号自动进入房间
* 小号进入人机房间后，开始检测右边的图片，是否有[房主房间]这个图片，然后点击入房

**房主房间是从小号的视角看见的，**打开AirTest软件，连接小号所在的虚拟机，使用touch截图
截图的应该是图中的蓝色区域
![image](https://github.com/user-attachments/assets/8ca59197-f66d-4cf9-a7bd-5ef064ecc8b7)

截图的范围参考我的截图范围
![房主房间](https://github.com/cndaqiang/WZRY/blob/master/assets/tpl1716782981770.png)

**Comment by cndaqiang** [comment]
@NonFelm 
我又补充了一些内容
https://github.com/cndaqiang/WZRY/issues/42#issuecomment-2418505810


如果你的问题解决了，回复解决了，或者关闭这个issues
没解决，就继续提问，
新的问题开辟新的issues
