### ISSUE TITLE
小号没有进入大号房间

### ISSUE THREAD

**Issue by NonFelm** [cndaqiang/WZRY#48]
我已 正确截图房主**头像房间两**个图片并替换，配置了**对战前插入文件**，配置了两个**config.0/1.txt**文件，并用wzry.py  config.0/1.txt分别在**两个cmd**打开。
但两个号都是直接点开始匹配，小号没有进入大号房间.
#
![屏幕截图 2024-10-20 112944](https://github.com/user-attachments/assets/3f4d212e-786e-4e0e-a1dc-9ead2bd2fa42)
![屏幕截图 2024-10-20 113238](https://github.com/user-attachments/assets/46c53112-8868-428d-8624-b2da8e94f623)
![屏幕截图 2024-10-20 113430](https://github.com/user-attachments/assets/e3dc683b-4d3a-4da9-a635-58e0a021a5fa)
![屏幕截图 2024-10-20 113700](https://github.com/user-attachments/assets/3f979f51-bcbf-4840-bfc5-87e36a2caedf)

**Comment by cndaqiang** [comment]
因为你没有开启组队模式，程序不知道一共有多少台模拟器.

使用这个配置文件[howto](https://cndaqiang.github.io/WZRY/howtorun.html):
![image](https://github.com/user-attachments/assets/cc2d6a80-7e95-415f-8a4f-1230d81f2fd1)

**Comment by cndaqiang** [comment]
![image](https://github.com/user-attachments/assets/a955cb53-f6af-40ac-b328-b2727f81b9a2)

**Comment by cndaqiang** [comment]
在程序执行的时候，会输出运行参数到屏幕上，在调试的时候，**如果屏幕上输出的组队模式=False**，你就停掉python。
免得进入了对战后，还要等待对战结束。
