### ISSUE TITLE
先打标准青铜再打星耀

### ISSUE THREAD

**Issue by NonFelm** [cndaqiang/WZRY#49]
先打一把**标准触摸青铜组队**，再打N把默认星耀组队。对局前插入文件该怎么写？

适用于：时间不多、只有热点开流量、想办任务睡一个午觉起来就结束运行的情况。

**Comment by cndaqiang** [comment]
在`WZRY.mynode.对战前插入.txt`中插入
```
self.青铜段位 = False
self.标准模式 = False
self.触摸对战 = False
if self.jinristep = 1: self.青铜段位 = True
if self.jinristep = 1: self.标准模式 = True
if self.jinristep = 1: self.触摸对战 = True
```

**Comment by NonFelm** [comment]
不行捏，进的还是快速模式
跟组队有关吗？
![屏幕截图 2024-10-21 122900](https://github.com/user-attachments/assets/6e6eb6b1-8b3d-4f70-b0e6-5a0e329ee082)

**Comment by cndaqiang** [comment]
我前面写错了，是`==`不是`=`
```
if self.jinristep == 1: self.青铜段位 = True
if self.jinristep == 1: self.标准模式 = True
if self.jinristep == 1: self.触摸对战 = True
```

**Comment by NonFelm** [comment]
第一把出来之后选的是 **青铜-快速**
没选 **星耀-标准**
![屏幕截图 2024-10-21 175336](https://github.com/user-attachments/assets/8e2f0cfa-526c-4c0f-8a2e-b2664474bc26)

**Comment by cndaqiang** [comment]
> 第一把出来之后选的是 **青铜** 没选 **星耀** ![屏幕截图 2024-10-21 175336](https://private-user-images.githubusercontent.com/147258869/378367427-8e2f0cfa-526c-4c0f-8a2e-b2664474bc26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDY0NTcsIm5iZiI6MTcyOTUwNjE1NywicGF0aCI6Ii8xNDcyNTg4NjkvMzc4MzY3NDI3LThlMmYwY2ZhLTUyNmMtNGMwZi04YTJlLWIyNjY0NDc0YmMyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQxMDIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDVlZTM3N2ZkMDE3YzIwZGMzY2YzOGM0NmQ3MDc1ZmVlYWZkZjYyODNkOTZlNzc1YWY3OGU3MDAwMGZmNTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.l8F60ynNbtNP6OmxWso-aDNDHmFGJIgMuHKVkUbWK9E)

@NonFelm hhhh，这次是你写错别字喽

False你写成了Flase

**Comment by NonFelm** [comment]
**(￣∇￣")**

**Comment by NonFelm** [comment]
第一把出来之后，**小号**没进大号房间，大号就自己开了。大号回到大厅再选模式又变成了 **青铜-快速**
![屏幕截图 2024-10-22 121139](https://github.com/user-attachments/assets/f56d4a52-cc6e-4be9-b56b-cfccbc9309c2)
![屏幕截图 2024-10-22 121312](https://github.com/user-attachments/assets/7159d1fa-e86d-42bc-802d-9bd4e3f58344)
