### ISSUE TITLE
运行的时候出现如下提示。

### ISSUE THREAD

**Issue by longbiteng** [cndaqiang/WZRY#50]
RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
模块[airtest_mobileauto]不存在, 尝试安装
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: airtest_mobileauto in d:\python\lib\site-packages (1.3.24)
Requirement already satisfied: airtest in d:\python\lib\site-packages (from airtest_mobileauto) (1.3.4)
Requirement already satisfied: numpy in d:\python\lib\site-packages (from airtest_mobileauto) (2.1.1)
Requirement already satisfied: Jinja2>=2.8 in d:\python\lib\site-packages (from airtest->airtest_mobileauto) (3.1.4)
Requirement already satisfied: Pillow>=3.4.0 in d:\python\lib\site-packages (from airtest->airtest_mobileauto) (10.4.0)
Requirement already satisfied: requests>=2.11.1 in d:\python\lib\site-packages (from airtest->airtest_mobileauto) (2.32.3)
Requirement already satisfied: six<=1.16.0,>=1.9.0 in d:\python\lib\site-packages (from airtest->airtest_mobileauto) (1.16.0)
Requirement already satisfied: mss==6.1.0 in d:\python\lib\site-packages (from airtest->airtest_mobileauto) (6.1.0)
Requirement already satisfied: opencv-contrib-python<=4.6.0.66,>=4.4.0.46 in d:\python\lib\site-packages (from airtest->airtest_mobileauto) (4.6.0.66)
Requirement already satisfied: facebook-wda>=1.3.3 in d:\python\lib\site-packages (from airtest->airtest_mobileauto) (1.4.9)
Requirement already satisfied: pywinauto==0.6.3 in d:\python\lib\site-packages (from airtest->airtest_mobileauto) (0.6.3)
Requirement already satisfied: filelock in d:\python\lib\site-packages (from airtest->airtest_mobileauto) (3.16.1)
Requirement already satisfied: ffmpeg-python in d:\python\lib\site-packages (from airtest->airtest_mobileauto) (0.2.0)
Requirement already satisfied: tidevice in d:\python\lib\site-packages (from airtest->airtest_mobileauto) (0.12.10)
Requirement already satisfied: psutil in d:\python\lib\site-packages (from airtest->airtest_mobileauto) (6.0.0)
Requirement already satisfied: pywin32 in d:\python\lib\site-packages (from airtest->airtest_mobileauto) (306)
Requirement already satisfied: comtypes in d:\python\lib\site-packages (from pywinauto==0.6.3->airtest->airtest_mobileauto) (1.4.7)
Requirement already satisfied: pypiwin32 in d:\python\lib\site-packages (from pywinauto==0.6.3->airtest->airtest_mobileauto) (223)
Requirement already satisfied: retry in d:\python\lib\site-packages (from facebook-wda>=1.3.3->airtest->airtest_mobileauto) (0.9.2)
Requirement already satisfied: cached-property~=1.5.1 in d:\python\lib\site-packages (from facebook-wda>=1.3.3->airtest->airtest_mobileauto) (1.5.2)
Requirement already satisfied: Deprecated~=1.2.6 in d:\python\lib\site-packages (from facebook-wda>=1.3.3->airtest->airtest_mobileauto) (1.2.14)
Requirement already satisfied: construct>=2 in d:\python\lib\site-packages (from facebook-wda>=1.3.3->airtest->airtest_mobileauto) (2.10.70)
Requirement already satisfied: MarkupSafe>=2.0 in d:\python\lib\site-packages (from Jinja2>=2.8->airtest->airtest_mobileauto) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\python\lib\site-packages (from requests>=2.11.1->airtest->airtest_mobileauto) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\python\lib\site-packages (from requests>=2.11.1->airtest->airtest_mobileauto) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\python\lib\site-packages (from requests>=2.11.1->airtest->airtest_mobileauto) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\python\lib\site-packages (from requests>=2.11.1->airtest->airtest_mobileauto) (2024.8.30)
Requirement already satisfied: future in d:\python\lib\site-packages (from ffmpeg-python->airtest->airtest_mobileauto) (1.0.0)
Requirement already satisfied: colored in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto) (2.2.4)
Requirement already satisfied: packaging in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto) (24.1)
Requirement already satisfied: tornado in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto) (6.4.1)
Requirement already satisfied: simple-tornado>=0.2.2 in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto) (0.2.2)
Requirement already satisfied: simplejson in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto) (3.19.3)
Requirement already satisfied: tabulate in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto) (0.9.0)
Requirement already satisfied: logzero in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto) (1.7.0)
Requirement already satisfied: deprecation in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto) (2.1.0)
Requirement already satisfied: wrapt<2,>=1.10 in d:\python\lib\site-packages (from Deprecated~=1.2.6->facebook-wda>=1.3.3->airtest->airtest_mobileauto) (1.16.0)
Requirement already satisfied: colorama in d:\python\lib\site-packages (from logzero->tidevice->airtest->airtest_mobileauto) (0.4.6)
Requirement already satisfied: decorator>=3.4.2 in d:\python\lib\site-packages (from retry->facebook-wda>=1.3.3->airtest->airtest_mobileauto) (5.1.1)
Requirement already satisfied: py<2.0.0,>=1.4.26 in d:\python\lib\site-packages (from retry->facebook-wda>=1.3.3->airtest->airtest_mobileauto) (1.11.0)
Traceback (most recent call last):
  File "G:\WZRY\wzry.py", line 2902, in <module>
    task_manager = TaskManager(config_file, wzry_task, 'RUN')
                   ^^^^^^^^^^^
NameError: name 'TaskManager' is not defined

**Comment by longbiteng** [comment]
大大，能出个视频简单介绍一下怎么运行吗。感谢啊

**Comment by cndaqiang** [comment]
@longbiteng 

* 兄弟，读一下[手册](https://github.com/cndaqiang/WZRY/blob/master/howtorun.md)啊, 第一条就是安装依赖
* 看完手册和常见问题，你就会了，真的写的很详细了
```
python -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple  --upgrade
```

**Comment by longbiteng** [comment]
G:\WZRY>python -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple  --upgrade
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: airtest_mobileauto>=1.3.19.1 in d:\python\lib\site-packages (from -r requirements.txt (line 1)) (1.3.24)
Requirement already satisfied: airtest in d:\python\lib\site-packages (from airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (1.3.4)
Requirement already satisfied: numpy in d:\python\lib\site-packages (from airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: Jinja2>=2.8 in d:\python\lib\site-packages (from airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (3.1.4)
Requirement already satisfied: Pillow>=3.4.0 in d:\python\lib\site-packages (from airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (10.4.0)
Requirement already satisfied: requests>=2.11.1 in d:\python\lib\site-packages (from airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (2.32.3)
Requirement already satisfied: six<=1.16.0,>=1.9.0 in d:\python\lib\site-packages (from airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: mss==6.1.0 in d:\python\lib\site-packages (from airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (6.1.0)
Requirement already satisfied: opencv-contrib-python<=4.6.0.66,>=4.4.0.46 in d:\python\lib\site-packages (from airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (4.6.0.66)
Requirement already satisfied: facebook-wda>=1.3.3 in d:\python\lib\site-packages (from airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (1.4.9)
Requirement already satisfied: pywinauto==0.6.3 in d:\python\lib\site-packages (from airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (0.6.3)
Requirement already satisfied: filelock in d:\python\lib\site-packages (from airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (3.16.1)
Requirement already satisfied: ffmpeg-python in d:\python\lib\site-packages (from airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (0.2.0)
Requirement already satisfied: tidevice in d:\python\lib\site-packages (from airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (0.12.10)
Requirement already satisfied: psutil in d:\python\lib\site-packages (from airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (6.0.0)
Requirement already satisfied: pywin32 in d:\python\lib\site-packages (from airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (306)
Requirement already satisfied: comtypes in d:\python\lib\site-packages (from pywinauto==0.6.3->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (1.4.7)
Requirement already satisfied: pypiwin32 in d:\python\lib\site-packages (from pywinauto==0.6.3->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (223)
Requirement already satisfied: retry in d:\python\lib\site-packages (from facebook-wda>=1.3.3->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (0.9.2)
Requirement already satisfied: cached-property~=1.5.1 in d:\python\lib\site-packages (from facebook-wda>=1.3.3->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (1.5.2)
Requirement already satisfied: Deprecated~=1.2.6 in d:\python\lib\site-packages (from facebook-wda>=1.3.3->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (1.2.14)
Requirement already satisfied: construct>=2 in d:\python\lib\site-packages (from facebook-wda>=1.3.3->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (2.10.70)
Requirement already satisfied: MarkupSafe>=2.0 in d:\python\lib\site-packages (from Jinja2>=2.8->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\python\lib\site-packages (from requests>=2.11.1->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\python\lib\site-packages (from requests>=2.11.1->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\python\lib\site-packages (from requests>=2.11.1->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\python\lib\site-packages (from requests>=2.11.1->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (2024.8.30)
Requirement already satisfied: future in d:\python\lib\site-packages (from ffmpeg-python->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: colored in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (2.2.4)
Requirement already satisfied: packaging in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (24.1)
Requirement already satisfied: tornado in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (6.4.1)
Requirement already satisfied: simple-tornado>=0.2.2 in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (0.2.2)
Requirement already satisfied: simplejson in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (3.19.3)
Requirement already satisfied: tabulate in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (0.9.0)
Requirement already satisfied: logzero in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (1.7.0)
Requirement already satisfied: deprecation in d:\python\lib\site-packages (from tidevice->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: wrapt<2,>=1.10 in d:\python\lib\site-packages (from Deprecated~=1.2.6->facebook-wda>=1.3.3->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: colorama in d:\python\lib\site-packages (from logzero->tidevice->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: decorator>=3.4.2 in d:\python\lib\site-packages (from retry->facebook-wda>=1.3.3->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (5.1.1)
Requirement already satisfied: py<2.0.0,>=1.4.26 in d:\python\lib\site-packages (from retry->facebook-wda>=1.3.3->airtest->airtest_mobileauto>=1.3.19.1->-r requirements.txt (line 1)) (1.11.0)

G:\WZRY>python -u wzry.py 配置文件
RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
模块[airtest_mobileauto]不存在, 尝试安装
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: airtest_mobileauto in d:\python\lib\site-packages (1.3.24)
Requirement already satisfied: airtest in d:\python\lib\site-packages (from airtest_mobileauto) (1.3.4)

按照您说的运行了，还是这个提示。能加个V远程指导一下吗。18663397778，可赞助项目，感谢！

**Comment by cndaqiang** [comment]
自用开源项目，不加好友

@longbiteng 真的不看手册？
![image](https://github.com/user-attachments/assets/e3b6bac2-5a05-4e80-9058-abbf9d3e4d5c)

**Comment by cndaqiang** [comment]
@longbiteng 你的这个报错是python的常见问题，不在本脚本的讨论范围内

![image](https://github.com/user-attachments/assets/c801752d-1e1b-4caa-8cbe-27f8a7400c12)

**Comment by longbiteng** [comment]
感谢大大辛苦指导，卸载python，重装anaonda已经稳定运行。感激不尽。
