### ISSUE TITLE
标准-星耀，组队进房失败

### ISSUE THREAD

**Issue by NonFelm** [cndaqiang/WZRY#51]
观察到：触摸青铜和触摸星耀的对局时间其实差不多。
#
想实现：**组队-标准-星耀**，第一把触摸，第二把及以后不触摸。还能省点心。
结果房间邀请进不去，两个号各自开了
![屏幕截图 2024-10-22 211959](https://github.com/user-attachments/assets/bf9aedc5-742b-4558-b016-1f85a99c08e7)
@cndaqiang

**Comment by cndaqiang** [comment]
@NonFelm 
![image](https://github.com/user-attachments/assets/a90636e7-6eea-4a7f-bdc6-f083aa5a5e3c)

你在这三行代码前面加#号，可以强制执行

* **注意：每个账号每天星耀限制10局，不同的账户剩余局数不同，因此我才限制组队只在青铜模式**
* 星耀局的组队没有意义
* * 刷人机任务，刷金币，刷熟练度，只用青铜局就够了
* * 蓝色熟练度提升到红色熟练度才需要星耀局人机，星耀局单人模式比组队模式的胜率更高，经验更多（毕竟除了你还有一个真人在打游戏）
