### ISSUE TITLE
在 self.jinristep == N的时候退出脚本

### ISSUE THREAD

**Issue by NonFelm** [cndaqiang/WZRY#52]
如题。

**Comment by cndaqiang** [comment]
@NonFelm 我看不懂啊
![image](https://github.com/user-attachments/assets/fad5c988-d7d7-4e45-9c3f-50913f1a28f6)

**Comment by NonFelm** [comment]
抱歉
#
我是想实现：self.jinristep＝某个数，就退出脚本，退出游戏。
![IMG_20241023_134601](https://github.com/user-attachments/assets/cc112ede-f387-41dc-b319-db768b12bd5c)

**Comment by cndaqiang** [comment]
* 在wzry.py所在目录，新建一个空文件`WZRY.oneday.txt`
* 在`WZRY.node.临时初始化.txt`中填写
```
#4是对战总次数
 self.jinristep >=  4:  self.对战时间[1]=self.对战时间[0]+0.1
```
* 更复杂的配置可以见 https://github.com/cndaqiang/WZRY/issues/13#issuecomment-2197922847
