### ISSUE TITLE
[windows][雷电模拟器][战令、活跃礼包无法领取]

### ISSUE THREAD

**Issue by NonFelm** [cndaqiang/WZRY#53]
- [x] 我已阅读[初阶教程](https://cndaqiang.github.io/WZRY/doc/WZRY.pdf)
- [x] 我已阅读[基础手册](https://cndaqiang.github.io/WZRY/howtorun.html)
- [x] 我已查看[常见问题收录](https://github.com/cndaqiang/WZRY/issues/42), 并未找到重复问题
- [x] 我已可以顺利控制一台模拟器进行对战

为了快速解决问题，请尽可能的提供这些内容，并礼貌**友善**的提问
* 执行结果 
![屏幕截图 2024-10-25 132255](https://github.com/user-attachments/assets/1b4f59b8-b40d-4d8e-be3f-7c4e0b1525ea)

* 配置文件
*  运行目录
![屏幕截图 2024-10-25 132530](https://github.com/user-attachments/assets/2a041f75-cf3c-4377-ac02-dd2a7344dc26)

* 游戏页面
![屏幕截图 2024-10-25 132730](https://github.com/user-attachments/assets/13219063-274c-4f40-9665-9cfff5f76b13)

**Comment by cndaqiang** [comment]
方法1. 截图替换
![image](https://github.com/user-attachments/assets/5991d60c-13a2-4977-a189-e31f4b75dd72)

方法2. 用我的字典替换掉你的字典。
[android.var_dict_0.txt](https://github.com/user-attachments/files/17516883/android.var_dict_0.txt)
