### ISSUE TITLE
[windows][雷电模拟器][增加功能][领完礼包关机]

### ISSUE THREAD

**Issue by NonFelm** [cndaqiang/WZRY#54]
**新增**：自动关机功能？
#
* cmd/powershell/terminal/vscode/pycharm等运行界面截图
![屏幕截图 2024-10-25 204636](https://github.com/user-attachments/assets/2711f5c4-75d6-45d0-ace2-01e2a9608905)

**Comment by cndaqiang** [comment]
及时阅读新增的说明书
![image](https://github.com/user-attachments/assets/b9781180-46af-41b5-aed3-99340002e8b1)

**没有你的配置文件，我无法帮你写出配置**

**Comment by cndaqiang** [comment]
https://github.com/cndaqiang/WZRY/issues/42#issuecomment-2437934763
