### ISSUE TITLE
想问下airtest_mobileauto是哪个版本的

### ISSUE THREAD

**Issue by NonFelm** [cndaqiang/WZRY#64]
之前装有1.3.24版本，使用 python -m pip install airtest_mobileauto --upgrade命令安装失败后索性卸载了原来的airtest_mobileauto
![屏幕截图 2024-11-15 235348](https://github.com/user-attachments/assets/e43a83c0-8523-4841-bcec-928683a376d2)
#
现在的安装直接找不到版本了 :D
![屏幕截图 2024-11-15 235414](https://github.com/user-attachments/assets/8dfd1069-b7fb-49da-9982-78ff3da4cd9b)

**Comment by cndaqiang** [comment]
使用最新`2.0.11`的就行，但是你好像是因为配置了代理才无法更新的

如果你网络不好，可以使用清华的源更新
```
python -m pip install  -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple  airtest_mobileauto --upgrade
```

![image](https://github.com/user-attachments/assets/1ed88382-9460-4d34-90c1-db85bf2abee7)
