### ISSUE TITLE
图片更新不生效

### ISSUE THREAD

**Issue by NonFelm** [cndaqiang/WZRY#66]
已配置WZRY.图片更新.txt和.pngtmp
却还是匹配不到**战令入口**
#
![屏幕截图 2024-11-16 131625](https://github.com/user-attachments/assets/0cd7c350-17cf-401b-afb2-b120748d273d)
![屏幕截图 2024-11-16 132215](https://github.com/user-attachments/assets/6d2644cf-bfbb-4ebf-922c-4d9f11a92458)
![tpl1731734235350](https://github.com/user-attachments/assets/a57e4884-3fd0-4d49-95d0-a7008053b501)

**Comment by cndaqiang** [comment]
**阅读不到完整的运行日志无法判断**

下面给一些建议

1. 注入错误，你的文件在.pngtmp里面, 注入template时要声明
![image](https://github.com/user-attachments/assets/f63fbb05-d099-45df-bac1-50781493a769)

2. 直接修改你的`android.var_dict_0.yaml`和`android.var_dict_1.yaml`, 使用我计算好的地址
```
(base) cndaqiang@vmnode:~$ python
Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> record_pos=(0.347, -0.105); resolution=(960, 540)
>>> x = 0.5*resolution[0]+record_pos[0]*resolution[0]
>>> y = 0.5*resolution[1]+record_pos[1]*resolution[0]
>>> pos = (x, y)
>>> pos
(813.12, 169.2)
```
即
![image](https://github.com/user-attachments/assets/2f310800-479f-4902-ab03-422d85e20c83)

3. 使用最新的2.2.8 版本
https://github.com/cndaqiang/WZRY/releases/tag/2.2.8
