### ISSUE TITLE
脚本无法关闭模拟器

### ISSUE THREAD

**Issue by NonFelm** [cndaqiang/WZRY#67]
领完礼包**游戏已退出**，但脚本无法关闭模拟器
#
![屏幕截图 2024-11-16 142652](https://github.com/user-attachments/assets/7036bd8d-f89f-4daa-927c-f016a0e71641)

**Comment by cndaqiang** [comment]
你写错了配置文件，但是你这种沟通方式的效率太低了
![image](https://github.com/user-attachments/assets/e2db183a-9c20-452d-a571-5cd2f329b879)

**Comment by NonFelm** [comment]
抱歉。
#
如果你完成这些内容, 请在`[ ]`内打上`x`, 即`[x]`
- [x] 我已阅读全新的[项目主页](https://cndaqiang.github.io/wzry.doc/)
- [x] 我已阅读全新的[安装指南](https://cndaqiang.github.io/wzry.doc/guide/install/)
- [x] 我已查看[常见问题收录](https://cndaqiang.github.io/wzry.doc/QA/), 并未找到重复问题
- [x] 我已升级脚本和依赖为[最新的版本](https://github.com/cndaqiang/WZRY/releases)
- [x] 我已可以顺利控制一台模拟器进行对战

## 为了快速解决问题，请尽可能的提供这些内容，并礼貌**友善**的提问
* 如果你可以为本项目点个[star](https://github.com/cndaqiang/WZRY), 我会更愉快的回答你的问题.


### 软件自2.2.0以来经历了巨大的更新, 版本小于2.2.0遇到的issues不予回复
* 建议采用[2.2.6](https://github.com/cndaqiang/WZRY/releases/tag/2.2.6)以及最新的stable版本.


### 配置文件截图
```
请在此处上传你的配置文件截图或者粘贴到此处
```
我的Pie_1是小号，扫码上的所以懒得改了...
![image](https://github.com/user-attachments/assets/8c12b260-819f-47bf-b090-a69ebab3e944)

### 执行结果
```
请在此处上传你的执行结果截图或者粘贴到此处
或者cmd/powershell/terminal/vscode/pycharm等运行界面报错等截图
```
![image](https://github.com/user-attachments/assets/826ab327-32d4-411c-95d5-f4c05122c71e)

### 运行目录
请在此处粘贴你的代码目录截图
![image](https://github.com/user-attachments/assets/c8451a06-faae-41fd-87f8-df216a7cb65f)

### 模拟器设置页面
* 请在此处粘贴你的模拟器设置页面.
![image](https://github.com/user-attachments/assets/8642d48a-f052-45af-9c36-c60fadd713a2)

* 需要确定你开启了ADB以及ADB的端口以及分辨率和dpi的设置.
![image](https://github.com/user-attachments/assets/fc0b551b-5bc8-4309-acca-984f24a533e8)
![image](https://github.com/user-attachments/assets/6cbd448f-e696-4c5d-b84a-54396108593b)
* 非`960x540`分辨率`dpi=160`的设备, 请自行解决.


### 游戏页面
请在此处粘贴你的游戏页面.

**Comment by cndaqiang** [comment]
第一点，你的1号模拟器，名字之间是有空格的
![image](https://github.com/user-attachments/assets/c9a6614f-8db0-4047-a2c6-687a0c8ae3a3)
但是你配置文件里没有这个空格
![image](https://github.com/user-attachments/assets/ab10baf0-b3c4-43be-adf7-4fea87dcd866)

第二，你模拟器的名字有s，配置文件里面没有s，所以关闭的时候，找不到你这台模拟器
![image](https://github.com/user-attachments/assets/abd8bace-679f-42fa-9897-502964fbd696)

![image](https://github.com/user-attachments/assets/c04600dc-0096-40ca-a01d-15e4039d0abd)
