### ISSUE TITLE
[windows][MUMU模拟器][无法循环选熟练度最低的英雄]

### ISSUE THREAD

**Issue by xjxhdgb** [cndaqiang/WZRY#69]
如果你完成这些内容, 请在`[ ]`内打上`x`, 即`[x]`
- [x] 我已阅读全新的[项目主页](https://cndaqiang.github.io/wzry.doc/)
- [x] 我已阅读全新的[安装指南](https://cndaqiang.github.io/wzry.doc/guide/install/)
- [x] 我已查看[常见问题收录](https://cndaqiang.github.io/wzry.doc/QA/), 并未找到重复问题
- [x] 我已升级脚本和依赖为[最新的版本](https://github.com/cndaqiang/WZRY/releases)
- [x] 我已可以顺利控制一台模拟器进行对战

## 为了快速解决问题，请尽可能的提供这些内容，并礼貌**友善**的提问
* 如果你可以为本项目点个[star](https://github.com/cndaqiang/WZRY), 我会更愉快的回答你的问题.

### 软件自2.2.0以来经历了巨大的更新, 版本小于2.2.0遇到的issues不予回复
* 建议采用[2.2.6](https://github.com/cndaqiang/WZRY/releases/tag/2.2.6)以及最新的stable版本.

### 配置文件截图

![image](https://github.com/user-attachments/assets/764583d5-ceee-44e1-83fc-d283975b1197)

请在此处上传你的配置文件截图或者粘贴到此处

### 执行结果

![image](https://github.com/user-attachments/assets/a55623ef-b9ce-492a-90ee-bc880409972d)

请在此处上传你的执行结果截图或者粘贴到此处
或者cmd/powershell/terminal/vscode/pycharm等运行界面报错等截图

### 运行目录
请在此处粘贴你的代码目录截图
![image](https://github.com/user-attachments/assets/9a1efc63-b67f-4612-81a5-66cc69febafb)

### 模拟器设置页面
* 请在此处粘贴你的模拟器设置页面.
* 需要确定你开启了ADB以及ADB的端口以及分辨率和dpi的设置.
* 非`960x540`分辨率`dpi=160`的设备, 请自行解决.
![image](https://github.com/user-attachments/assets/634440fd-ac9f-4d12-8790-1bfea9ee8bfb)
![image](https://github.com/user-attachments/assets/9c58d46d-7fc7-4db4-82af-aedbb3f9d839)

### 游戏页面
请在此处粘贴你的游戏页面.
![image](https://github.com/user-attachments/assets/b5778e4d-5768-4faf-89a4-2a3e589751a8)

**Comment by xjxhdgb** [comment]
配置文件截图
![image](https://github.com/user-attachments/assets/5b7cbe61-8b1e-4a16-a04f-b67c7a20077d)
执行结果
![image](https://github.com/user-attachments/assets/b46a7449-2e66-40c7-adca-784e9029f50c)

**Comment by cndaqiang** [comment]
额外补充，你的`WZRY.0.运行模式.txt`里面包含2.2.8版本的功能，比如`灵宝互动`

也许你可以尝试使用最新的2.2.8版本了，我测试的结果还挺稳定的

https://github.com/cndaqiang/WZRY/releases/tag/2.2.8
