### ISSUE TITLE
超过23时后无法组队

### ISSUE THREAD

**Issue by NonFelm** [cndaqiang/WZRY#76]
如果你完成这些内容, 请在`[ ]`内打上`x`, 即`[x]`
- [x] 我已阅读全新的[项目主页](https://cndaqiang.github.io/wzry.doc/)
- [x] 我已阅读全新的[安装指南](https://cndaqiang.github.io/wzry.doc/guide/install/)
- [x] 我已搜索[常见问题收录](https://cndaqiang.github.io/wzry.doc/qa/qa), 并未找到类似问题

## 为了快速解决问题
* 请礼貌**友善**的提问

**实现：23时后继续组队**

### 你使用的脚本版本
WZRY-2.7.7

### 配置文件: `config.win.yaml`
> 请在此处上传你的配置文件`config.win.yaml`截图或者粘贴到此处
![0](https://github.com/user-attachments/assets/aaa11c86-698f-4cb1-96aa-ffcdefc4f7a0)

### 执行结果: `result.0.txt`
> **如果你能提供完整的执行结果最好了**
> 请在此处上传你的执行结果`result.0.txt`
> 或者截图cmd/powershell/terminal/vscode/pycharm等运行界面报错
![屏幕截图 2024-11-20 232352](https://github.com/user-attachments/assets/75816203-94a6-4814-b93f-958cd8192d88)

### 运行目录
> 请在此处粘贴你的代码目录截图
![2](https://github.com/user-attachments/assets/5e8b0322-b81b-4f0a-a60a-845144422151)

### 模拟器设置页面
* **如果你涉及到连接不了模拟器，无法控制模拟器的问题，请在此处粘贴你的模拟器设置页面.**
* 需要确定你开启了ADB以及ADB的端口以及分辨率和dpi的设置.
* 非`960x540`分辨率`dpi=160`的设备, 请自行解决.
* 模拟器的安装路径, 多开页面截图等
![屏幕截图 2024-11-21 171539](https://github.com/user-attachments/assets/5b46ccaa-b9bc-42e4-b44e-ede5192ac486)
![屏幕截图 2024-11-21 171616](https://github.com/user-attachments/assets/3eafd6cb-be02-41ef-b24d-82d0a5bd0856)
![屏幕截图 2024-11-21 171645](https://github.com/user-attachments/assets/c18ff497-7d3b-471f-9c61-32ad10874229)

**Comment by cndaqiang** [comment]
你的self.对战时间设置直到23点，每个账户都停了，就没法组队了


https://wzry-doc.pages.dev/guide/file/

https://wzry-doc.pages.dev/guide/zudui/

在每一个的账户的[WZRY.mynode.运行模式.txt](https://wzry-doc.pages.dev/guide/file/)中都插入
```
# 所有账户的对战时间
self.对战时间=[0.1,23.99]
self.限时组队时间=23.99
```

**Comment by cndaqiang** [comment]
PS. 你在用2.7.7版本, 被我优化后以2.2.8发布了(2.7.7其实是2.2.7我打错版本号了)
